service: circuitverse
image: vaibhavupreti/circuitverse
servers:
  - <%= ENV.fetch("SERVER_IP") %>
registry:
  server: ghcr.io
  username: vaibhavupreti
  password:
    - MRSK_GHCR_REGISTRY_PASSWORD

env:
   clear:
     MEOW: meow    
     # REDIS_URL: redis://:6379/0
   secret:
     - RAILS_MASTER_KEY
     - REDIS_URL
     - POSTGRES_URL
# Use a different ssh user than root
ssh:
  user: ubuntu

builder:
  dockerfile: Dockerfile.production

accessories:
  yosys2digitaljs-server:
    image: ghcr.io/circuitverse/yosys2digitaljs-server:master
    host: <%= ENV.fetch("SERVER_IP") %>
    port: 2812
