service: circuitverse
image: vaibhavupreti/circuitverse
servers:
  - <%= ENV["SERVER_IP"] %>
registry:
  server: ghcr.io
  username: vaibhavupreti
  password:
    - MRSK_GHCR_REGISTRY_PASSWORD

env:
   clear:
     MEOW: meow
     # REDIS_URL: redis://:6379/0
   secret:
     - RAILS_MASTER_KEY
     - REDIS_URL
     - POSTGRES_URL
     - AWS_S3_ACCESS_KEY_ID
     - AWS_S3_SECRET_ACCESS_KEY

ssh:
  user: ubuntu

builder:
  remote:
    arch: amd64
    host: ssh://ubuntu@34.210.157.109
  dockerfile: Dockerfile.production

accessories:
  yosys2digitaljs-server:
    image: ghcr.io/circuitverse/yosys2digitaljs-server:master
    host: <%= ENV["SERVER_IP"] %>
    port: 2812
