service: circuitverse
image: vaibhavupreti/circuitverse
servers:
  web:
    hosts:
      - <%= ENV["SERVER_IP"] %>
    cmd: ./bin/rails server -b 0.0.0.0 -p 3000
    labels:
      traefik.http.routers.circuitverse-web.rule: Host(`cv-mrsk.vaibhavupreti.me`)
    options:
      add-host: host.docker.internal:host-gateway
  sidekiq:
    hosts:
      - <%= ENV["SERVER_IP"] %>
    options:
      add-host: host.docker.internal:host-gateway
    cmd: bundle exec sidekiq -e production -q default -q mailers

registry:
  server: ghcr.io
  username: vaibhavupreti
  password:
    - KAMAL_GHCR_REGISTRY_PASSWORD

env:
  clear:
    RAILS_SERVE_STATIC_FILES: true
    REDIS_URL: "redis://host.docker.internal:6379/0"
    YOSYS_PATH: "http://host.docker.internal:3040"
    POSTGRES_URL: "postgresql://postgres:postgres@host.docker.internal:5432/circuitverse_production"
    AWS_REGION: 'us-west-2'
    AWS_REGION_SES: 'ap-south-1'
    CIRCUITVERSE_EMAIL_ID: 'support@circuitverse.org'
    AWS_S3_REGION: 'us-west-2'
    AWS_S3_BUCKET_NAME: 'circuitverse-development'
  secret:
    - RAILS_MASTER_KEY
    - AWS_S3_ACCESS_KEY_ID
    - AWS_S3_SECRET_ACCESS_KEY
    - SECRET_KEY_BASE
    - BUGSNAG_API_KEY
    - RECAPTCHA_SITE_KEY
    - RECAPTCHA_SECRET_KEY
    - VAPID_PUBLIC_KEY
    - VAPID_PRIVATE_KEY

ssh:
  user: ubuntu

builder:
  dockerfile: Dockerfile.production

accessories:
  yosys2digitaljs-server:
    image: ghcr.io/circuitverse/yosys2digitaljs-server:master
    host: <%= ENV["SERVER_IP"] %>
    port: 3040
    options:
      add-host: host.docker.internal:host-gateway

traefik:
  options:
    memory: 512m

healthcheck:
  port: 3000
  max_attempts: 8
