service: circuitverse
image: vaibhavupreti/circuitverse
servers:
  web:
    - <%= ENV["SERVER_IP"] %>
  #sidekiq:
  #  hosts:
  #    - host.ip
  #  cmd: bundle exec sidekiq -e production -q default -q mailers -d -L tmp/sidekiq.log
  #  options:
  #    cap-add: true
  #    cpu-count: 4
  #
  # docker run ... --cap-add --cpu-count 4 ...

registry:
  server: ghcr.io
  username: vaibhavupreti
  password:
    - MRSK_GHCR_REGISTRY_PASSWORD

env:
   clear:
     RAILS_SERVE_STATIC_FILES: true
     RAILS_LOG_TO_STDOUT: 1
     PORT: 3001
   secret:
     - RAILS_MASTER_KEY
     - REDIS_URL
     - POSTGRES_URL
     - AWS_S3_ACCESS_KEY_ID
     - AWS_S3_SECRET_ACCESS_KEY
     - SECRET_KEY_BASE

ssh:
  user: ubuntu

builder:
  dockerfile: Dockerfile.production

accessories:
  yosys2digitaljs-server:
    image: ghcr.io/circuitverse/yosys2digitaljs-server:master
    host: <%= ENV["SERVER_IP"] %>
    port: 2812

healthcheck:
  max_attempts: 8
