name: Deploy to Server
on:
  push:
    branches: [ main ] # change to master
    tags: ['v*.*.*']

  workflow_dispatch:
  # workflow_dispatch: # limitation: cannot access tags from another workflows
    # https://github.com/orgs/community/discussions/27028

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  build-production:
    # runs-on: ubuntu-latest
    uses: vaibhavupreti/CircuitVerse/.github/workflows/docker-publish.yml@main

            #  tags: ghcr.io/vaibhavupreti/circuitverse:${{ github.sha }},ghcr.io/vaibhavupreti/circuitverse:latest
            # labels: ${{ steps.meta.outputs.labels }}

  deploy-production:
    needs: build-production
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://cv-mrsk.vaibhavupreti.me

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Copy sample database configuration
        run: cp config/database.example.yml config/database.yml

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'

      - name: Install mrsk
        run: gem install mrsk

      - name: Deploy with mrsk
        run: |
          mrsk lock release
          mrsk deploy -vvvv --skip_push
        env:
          RAILS_SERVE_STATIC_FILES: true
          AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}
          MRSK_GHCR_REGISTRY_PASSWORD: ${{ secrets.MRSK_GHCR_REGISTRY_PASSWORD }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
          RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY }}
          RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}
